# Generated by Django 6.0.1 on 2026-01-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_remove_addoncourse_created_by_and_more'),
        ('student', '0003_student_role_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='purchased_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='principal.addoncourse'),
        ),
    ]
