# Generated by Django 6.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_remove_addoncourse_created_by_and_more'),
        ('student', '0004_student_purchased_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.addoncourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='purchased_courses',
        ),
        migrations.AddField(
            model_name='student',
            name='purchased_courses',
            field=models.ManyToManyField(blank=True, related_name='students', through='student.StudentCourse', to='principal.addoncourse'),
        ),
    ]
