# Generated by Django 6.0.1 on 2026-01-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_addoncourse_course_id_addoncourse_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addoncourse',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='addoncourse',
            name='status',
        ),
    ]
